site_name: Tiny Basic for Arduino
site_description: A Tiny Basic interpreter for Mid-range Arduino boards
site_author: Dilshan R Jayakody
copyright: 'An open-source project by <a href="https://github.com/dilshan/" target="_blank" rel="noopener noreferrer">Dilshan R Jayakody</a>. | Contribute on <a target="_blank" rel="noopener noreferrer" href="https://github.com/dilshan/tiny-basic/">GitHub</a>.'

repo_url: https://github.com/dilshan/tiny-basic 
repo_name: dilshan/tiny-basic

theme:
  name: material
  logo: logo/tinybasic.png
  favicon: logo/tinybasic.png
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - toc.integrate

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite

nav:
  - Home: index.md
  - Documentation:
    - Overview: manual/index.md
    - In-Hardware Editor: manual/editor.md
    - Language Reference: manual/language-reference.md
    - Functions: manual/function-list.md
  - Platforms:
    - Arduino Due: platforms/due.md
    - Arduino Uno R4 WiFi: platforms/r4wifi.md
  - Support: https://github.com/dilshan/tiny-basic/issues

extra:
  generator: false