[platformio]
default_envs = due

[env:due]
platform = atmelsam
board = due
framework = arduino

extra_scripts = pre:parser_util.py

[env:native]
platform = native
build_flags = -DNATIVE -D_GNU_SOURCE -lfl

extra_scripts = pre:parser_util.py